export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const FILTER_ARTICLES_BY_ID = 'FILTER_ARTICLES_BY_ID'

export const FILTER_ARTICLES_BY_RANGE = 'FILTER_ARTICLES_BY_RANGE'