export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const ARTICLES_FILTER_BY_DATE = 'ARTICLES_FILTER_BY_DATE'

export const ARTICLES_FILTER_BY_KEYS = 'ARTICLES_FILTER_BY_KEYS'