export const INCREMENT = 'INCREMENT'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const SELECT_ARTICLE_FILTER = 'SELECT_ARTICLE_FILTER'
export const SELECT_ARTICLE_DATE_FILTER = 'SELECT_ARTICLE_DATE_FILTER'

export const FILTER_ARCICLES = 'FILTER_ARCICLES'